# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: Detect_FTP_get_cmd
# label used for menu selection
label: Detect FTP get command custom signature (Custom Threat ID 41063)
description: This skillet adds detection of the FTP get command to Custom Signatures

# type of device configuration
# common types are panorama, panos, and template
# https://github.com/PaloAltoNetworks/panhandler/blob/develop/docs/metadata_configuration.rst
type: panos
# preload static or default-based templates
extends:

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - Custom Vulnerability Signatures

variables:
  # This Skillet installs a custom threat signature that alerts on the FTP
  # get command. It does so via the ftp-req-cmd, and looks for RETR. 
  # There are no variables in this skillet.

# ---------------------------------------------------------------------
# end of preamble section

# snippets section
# ---------------------------------------------------------------------
# snippets used for api configuration including xpath and element as file name
# files will load in the order listed
snippets:
  - name: Detect_FTP_get_cmd
    xpath: /config/shared/threats/vulnerability
    file: ftp_get_vuln.xml
# ---------------------------------------------------------------------
# end of snippets section